name: gtin_toolkit
description: A toolkit for validate, generate and check GTIN's. This project indeeds to be; stable, easy to use and fast (when possible).
version: 1.0.3
homepage: https://github.com/vinicioslc/gtin-toolkit-dart/

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: 1.15.1
